### ISSUE TITLE
About conflict with the module "N98_CheckoutFilters"

### ISSUE THREAD

**Issue by mozgbrasil** [netz98/N98_CheckoutFilters#10]
Hello, good morning my friend

-

About conflict with the module "N98_CheckoutFilters"

-

I installed the following module

https://github.com/Adyen/adyen-magento

Then I installed the module

https://github.com/netz98/N98_CheckoutFilters

After I set the "Min age" parameter in the method configuration, the checkout error is displayed according to the images

This error is only occurring when the Adyen method is active for the native Magento methods the error is not triggered

-

Fatal error: Uncaught Error: Call to a member function getCustomerDob() on null in /public_html/magento-1.9.3.1-dev34/vendor/n98/N98_CheckoutFilters/src/app/code/community/N98/CheckoutFilters/Model/Payment/Method/Filter/Customer/Age.php:48 Stack trace: #0 /public_html/magento-1.9.3.1-dev34/vendor/n98/N98_CheckoutFilters/src/app/code/community/N98/CheckoutFilters/Model/Payment/Observer.php(54): N98_CheckoutFilters_Model_Payment_Method_Filter_Customer_Age->filter() #1 /public_html/magento-1.9.3.1-dev34/vendor/n98/N98_CheckoutFilters/src/app/code/community/N98/CheckoutFilters/Model/Payment/Observer.php(33): N98_CheckoutFilters_Model_Payment_Observer->_addFilter('n98_checkoutfil...', Object(Varien_Event_Observer)) #2 /public_html/magento-1.9.3.1-dev34/root/app/code/core/Mage/Core/Model/App.php(1358): N98_CheckoutFilters_Model_Payment_Observer->methodIsAvailable(Object(Varien_Event_Observer)) #3 /public_html/magento-1.9.3.1-dev34/root/app in /public_html/magento-1.9.3.1-dev34/vendor/n98/N98_CheckoutFilters/src/app/code/community/N98/CheckoutFilters/Model/Payment/Method/Filter/Customer/Age.php on line 48

-

Would you have any information on the reason for the occurrence?

-
![captura de tela de 2017-01-20 16-02-45](https://cloud.githubusercontent.com/assets/17202780/22160225/a147d42c-df2b-11e6-8cd9-f367849f8055.png)
![captura de tela de 2017-01-20 16-03-01](https://cloud.githubusercontent.com/assets/17202780/22160226/a149e42e-df2b-11e6-9fae-b10cf2c4f9e4.png)
![captura de tela de 2017-01-20 16-03-08](https://cloud.githubusercontent.com/assets/17202780/22160227/a1500e58-df2b-11e6-8f12-8908707aa567.png)

**Comment by mozgbrasil** [comment]
You can disregard my questioning

I just sent Pull Request to Adyen

Https://github.com/Adyen/adyen-magento/pull/734
